name: 'hex.pm publish - Elixir 1.14'
description: 'Publish elixir packages to hex.pm'
author: 'YannickFricke'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'purple'
